# Generated by Django 5.1.6 on 2025-03-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistprofile',
            options={'verbose_name': 'Artist Profile', 'verbose_name_plural': 'Artist Profiles'},
        ),
    ]
