# Generated by Django 5.1.6 on 2025-03-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_artistprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='stripe_secret_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
