# Generated by Django 5.1.6 on 2025-03-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyer Order', 'verbose_name_plural': 'Buyer Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Buyer Order Item', 'verbose_name_plural': 'Buyer Orders Items'},
        ),
    ]
