# Generated by Django 5.1.6 on 2025-03-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Buyer Order Item', 'verbose_name_plural': 'Buyer Order Items'},
        ),
    ]
