# Generated by Django 5.1.6 on 2025-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
