# Generated by Django 5.1.6 on 2025-03-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_paypal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paypal_id',
        ),
    ]
