# Generated by Django 5.1.6 on 2025-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_paypal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'paid'), ('Not Paid', 'not_paid')], default='Not Paid', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Shipped', 'shipped'), ('Delivered', 'delivered'), ('Canceled', 'canceled')], default='Pending', max_length=20),
        ),
    ]
