# Generated by Django 5.1.6 on 2025-03-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
